import React from 'react';
import type { CaseState, CaseImage } from '../types/case';
import { Button } from '../components/ui/Button';
import './Report.css';
import type { XRayInferenceOutput } from '../services/api';

interface ReportProps {
  caseState: CaseState;
  onNewCase: () => void;
  onBack: () => void;
}

const Provenance: React.FC<{type: 'AI'|'MEASURED'|'CALCULATED'|'CATALOG'|'USER'|'DICOM'}> = ({type}) => (
  <span style={{ fontSize: 9, background: 'rgba(0,0,0,0.06)', color: 'var(--color-text-secondary)', padding: '2px 5px', borderRadius: 4, marginLeft: 6, fontWeight: 700, letterSpacing: '0.05em', whiteSpace: 'nowrap' }}>[{type}]</span>
);

export const Report: React.FC<ReportProps> = ({ caseState, onNewCase, onBack }) => {
  const plan = caseState.planning;
  const isPlanEmpty = !plan || Object.keys(plan).length === 0;

  const renderImageSummary = (img: CaseImage) => {
    const isXRay = img.metadata?.modality !== 'MRI';
    
    return (
      <div key={img.id} className="rp-study-card">
        <h4 style={{ wordBreak: 'break-all', display: 'flex', justifyContent: 'space-between' }}>
          <span>{isXRay ? 'Radiograph (X-Ray)' : (img.metadata?.modality || 'UNKNOWN')}</span>
          <span style={{ fontWeight: 400, color: 'var(--color-text-secondary)', fontSize: 13 }}>{img.file?.name || 'Image'}</span>
        </h4>
        
        {!isXRay && (
          <div className="rp-study-grid">
            <div className="rp-study-col">
              <span className="rp-label">Femur Width</span>
              <span className="rp-val">{img.measurements.bones?.femur?.width_mm ? `${img.measurements.bones.femur.width_mm.toFixed(1)} mm` : 'N/A'}</span>
            </div>
            <div className="rp-study-col">
              <span className="rp-label">Tibia Width</span>
              <span className="rp-val">{img.measurements.bones?.tibia?.width_mm ? `${img.measurements.bones.tibia.width_mm.toFixed(1)} mm` : 'N/A'}</span>
            </div>
            <div className="rp-study-col">
              <span className="rp-label">Medial Meniscus</span>
              <span className="rp-val">{img.measurements.meniscus ? (img.measurements.meniscus.mean_thickness_mm ? `${img.measurements.meniscus.mean_thickness_mm.toFixed(1)} mm` : 'N/A') : 'Not applicable'}</span>
            </div>
          </div>
        )}
        {isXRay && (
          <div style={{ fontSize: 13, color: 'var(--color-text-secondary)' }}>Physical measurements must be manually calibrated during planning.</div>
        )}
      </div>
    );
  };

  const currentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

  return (
    <div className="rp-container fade-in">
      <div className="rp-document">
        
        <div className="rp-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <h1>Automated Case Report</h1>
            <p>Generated by Knee AI Clinical Workstation</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: 10, letterSpacing: '0.05em', color: 'rgba(255,255,255,0.5)', textTransform: 'uppercase', marginBottom: 2 }}>Date of Report</div>
            <div style={{ fontSize: 14, fontWeight: 500 }}>{currentDate}</div>
            <div style={{ fontSize: 10, letterSpacing: '0.05em', color: 'rgba(255,255,255,0.5)', textTransform: 'uppercase', marginTop: 12, marginBottom: 2 }}>Case Reference</div>
            <div style={{ fontSize: 14, fontWeight: 500, fontFamily: 'monospace' }}>{caseState.caseId}</div>
          </div>
        </div>

        <div className="rp-section" style={{ background: '#F8FAFC' }}>
          <h2>Patient Demographics</h2>
          <div className="rp-grid">
            <div className="rp-item">
              <span className="rp-label">Patient ID</span>
              <span className="rp-val">{caseState.patient?.patientId || 'ANONYMOUS'}</span>
            </div>
            <div className="rp-item">
              <span className="rp-label">Patient Name</span>
              <span className="rp-val">{caseState.patient?.name || 'ANONYMOUS'}</span>
            </div>
            <div className="rp-item">
              <span className="rp-label">Age</span>
              <span className="rp-val">{caseState.patient?.age ? `${caseState.patient.age} Y` : 'UNKNOWN'}</span>
            </div>
            <div className="rp-item">
              <span className="rp-label">Sex</span>
              <span className="rp-val">{caseState.patient?.sex?.toUpperCase() || 'UNKNOWN'}</span>
            </div>
          </div>
        </div>

        <div className="rp-section">
          <h2>Processed Imaging Studies</h2>
          <div className="rp-studies-list">
            {caseState.images.length > 0
              ? caseState.images.map(renderImageSummary)
              : <p style={{ color: 'var(--color-text-secondary)', fontSize: 14 }}>No images uploaded.</p>
            }
          </div>
        </div>
        
        {Object.values(caseState.xrayAnalysis || {}).length > 0 && (
          <div className="rp-section">
            <h2 style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
              <span>AI-Assisted Radiographic Findings</span>
              <span style={{ fontSize: 9, background: '#E0E7FF', color: '#3730A3', padding: '3px 8px', borderRadius: 4, letterSpacing: 0.05 }}>DENSENET121_KL_V1</span>
            </h2>
            <div className="rp-studies-list">
              {Object.values(caseState.xrayAnalysis || {}).map((xray: XRayInferenceOutput, idx: number) => {
                const imgName = caseState.images.find(i => i.id === xray.image_id)?.file?.name || 'Image';
                const isUncertain = xray.status === "AI_ASSESSMENT_UNCERTAIN";
                const isError = xray.status === "MODEL_NOT_READY" || xray.status === "INFERENCE_FAILED" || xray.status === "IMAGE_QUALITY_INSUFFICIENT";
                
                return (
                  <div key={idx} className="rp-study-card" style={{ padding: 24, background: 'var(--color-surface)', boxShadow: '0 1px 3px rgba(0,0,0,0.05)' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24, paddingBottom: 16, borderBottom: '1px solid var(--color-border)' }}>
                      <span style={{ fontSize: 13, color: 'var(--color-text-secondary)', fontWeight: 500 }}>Source: {imgName}</span>
                      <span style={{ fontSize: 11, fontWeight: 700, padding: '4px 10px', borderRadius: 12, background: isUncertain ? '#FFFBEB' : isError ? '#FEF2F2' : '#ECFDF5', color: isUncertain ? '#B45309' : isError ? '#991B1B' : '#065F46' }}>
                        {xray.status.replace(/_/g, ' ')}
                      </span>
                    </div>

                    {!isError && (
                      <div style={{ display: 'flex', gap: 32, flexWrap: 'wrap' }}>
                        
                        {/* Primary Result Box */}
                        <div style={{ flex: '1 1 200px', padding: 20, background: isUncertain ? '#F9FAFB' : 'var(--color-primary-soft)', borderRadius: 8, border: `1px solid ${isUncertain ? 'var(--color-border)' : '#BFDBFE'}` }}>
                          <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--color-text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 4 }}>Predicted Severity</div>
                          <div style={{ fontSize: 28, fontWeight: 700, color: isUncertain ? 'var(--color-text-secondary)' : 'var(--color-primary)', display: 'flex', alignItems: 'center' }}>
                            {xray.predicted_kl_grade !== null ? `KL Grade ${xray.predicted_kl_grade}` : 'Uncertain'}
                            <Provenance type="AI" />
                          </div>
                          {xray.confidence !== null && (
                            <div style={{ marginTop: 8, fontSize: 13, color: 'var(--color-text)', fontWeight: 500 }}>
                              Confidence: <span style={{ color: isUncertain ? '#B45309' : 'var(--color-text)' }}>{(xray.confidence * 100).toFixed(1)}%</span>
                            </div>
                          )}
                        </div>

                        {/* Probabilities Distribution */}
                        {xray.probabilities && (
                          <div style={{ flex: '2 1 300px' }}>
                            <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--color-text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 12 }}>Probability Distribution</div>
                            {[0, 1, 2, 3, 4].map((kl) => {
                              const prob = (xray.probabilities as any)[`KL${kl}`];
                              const isHighest = kl === xray.predicted_kl_grade;
                              return (
                                <div key={kl} style={{ display: 'flex', alignItems: 'center', marginBottom: 8 }}>
                                  <div style={{ width: 40, fontSize: 12, fontWeight: isHighest ? 700 : 500, color: isHighest ? 'var(--color-primary)' : 'var(--color-text)' }}>KL {kl}</div>
                                  <div style={{ flex: 1, background: '#F1F5F9', height: 8, borderRadius: 4, overflow: 'hidden', marginRight: 12 }}>
                                    <div style={{ width: `${prob * 100}%`, background: isHighest ? 'var(--color-primary)' : '#94A3B8', height: '100%', borderRadius: 4 }}></div>
                                  </div>
                                  <div style={{ width: 45, fontSize: 12, textAlign: 'right', fontWeight: isHighest ? 700 : 400, color: isHighest ? 'var(--color-primary)' : 'var(--color-text-secondary)' }}>
                                    {(prob * 100).toFixed(1)}%
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        )}

                      </div>
                    )}

                    <div className="rp-notes" style={{ marginTop: 24, background: '#F8FAFC', border: '1px solid var(--color-border)' }}>
                      <strong>Interpretative Findings</strong>
                      {xray.message}
                    </div>

                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* NEW SURGICAL PLAN SECTION */}
        <div className="rp-section">
          <h2>Surgical Planning Strategy</h2>
          {!isPlanEmpty ? (
            <div className="rp-studies-list">
              <div className="rp-study-card">
                
                {/* Validation Warning */}
                <div style={{ padding: 12, borderRadius: 6, marginBottom: 20, background: '#FEF2F2', border: '1px solid #FECACA' }}>
                   <div style={{ fontSize: 12, fontWeight: 700, color: '#991B1B', marginBottom: 4 }}>PLANNING STATUS: INCOMPLETE</div>
                   <div style={{ fontSize: 12, color: '#7F1D1D' }}>This surgical plan is mathematically incomplete and cannot be certified for clinical review.</div>
                   <ul style={{ margin: '8px 0 0 16px', padding: 0, fontSize: 12, color: '#991B1B' }}>
                     <li><strong>Dimensional Mapping:</strong> UNAVAILABLE</li>
                     <li><strong>Validated Implant Geometry:</strong> UNAVAILABLE</li>
                     <li><strong>HKA Mechanical Axis:</strong> UNAVAILABLE</li>
                   </ul>
                </div>

                <div className="rp-study-grid">
                  <div className="rp-study-col">
                    <span className="rp-label">Calibration Scale</span>
                    <span className="rp-val" style={{ display: 'flex', alignItems: 'center' }}>
                      {(plan.calibration?.mmPerPixelX || plan.calibration?.pixelsPerMm) ? `${(1/(plan.calibration.pixelsPerMm || 1)).toFixed(2)} mm/px` : 'UNAVAILABLE'}
                      {(plan.calibration?.mmPerPixelX || plan.calibration?.pixelsPerMm) && <Provenance type={plan.calibration.source === 'DICOM_PIXEL_SPACING' ? 'DICOM' : 'USER'} />}
                    </span>
                  </div>
                  <div className="rp-study-col">
                    <span className="rp-label">Alignment Philosophy</span>
                    <span className="rp-val">{plan.alignmentStrategy || 'Mechanical'}</span>
                  </div>
                  <div className="rp-study-col">
                    <span className="rp-label">Mechanical Axis (HKA)</span>
                    <span className="rp-val" style={{ color: 'var(--color-danger)' }}>UNAVAILABLE</span>
                  </div>
                </div>

                <div className="rp-study-grid" style={{ marginTop: 16, paddingTop: 16, borderTop: '1px solid var(--color-border)' }}>
                  <div className="rp-study-col">
                    <span className="rp-label">Joint Line Width</span>
                    <span className="rp-val" style={{ display: 'flex', alignItems: 'center' }}>
                      {plan.measurements?.jointLineWidth?.value ? `${plan.measurements.jointLineWidth.value} mm` : 'UNAVAILABLE'}
                      {plan.measurements?.jointLineWidth && <Provenance type="CALCULATED" />}
                    </span>
                  </div>
                  <div className="rp-study-col">
                    <span className="rp-label">Tibial Width</span>
                    <span className="rp-val" style={{ display: 'flex', alignItems: 'center' }}>
                      {plan.measurements?.tibialWidth?.value ? `${plan.measurements.tibialWidth.value} mm` : 'UNAVAILABLE'}
                      {plan.measurements?.tibialWidth && <Provenance type="CALCULATED" />}
                    </span>
                  </div>
                </div>

                <div className="rp-study-grid" style={{ marginTop: 16, paddingTop: 16, borderTop: '1px solid var(--color-border)' }}>
                  <div className="rp-study-col">
                    <span className="rp-label">Selected Femoral Component</span>
                    <span className="rp-val" style={{ display: 'flex', alignItems: 'center' }}>
                      {plan.implantSelection?.femoralId || 'NONE SELECTED'}
                      {plan.implantSelection?.femoralId && <Provenance type="USER" />}
                    </span>
                  </div>
                  <div className="rp-study-col">
                    <span className="rp-label">Selected Tibial Component</span>
                    <span className="rp-val" style={{ display: 'flex', alignItems: 'center' }}>
                      {plan.implantSelection?.tibialId || 'NONE SELECTED'}
                      {plan.implantSelection?.tibialId && <Provenance type="USER" />}
                    </span>
                  </div>
                </div>

                {plan.notes && (
                  <div style={{ marginTop: 24, fontSize: 13 }}>
                    <strong style={{ display: 'block', marginBottom: 8, color: 'var(--color-text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em', fontSize: 11 }}>Clinical Notes</strong>
                    <div style={{ padding: 12, background: '#F8FAFC', border: '1px solid var(--color-border)', borderRadius: 6, whiteSpace: 'pre-wrap' }}>
                      {plan.notes}
                    </div>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <p style={{ color: 'var(--color-text-secondary)', fontSize: 14 }}>No surgical plan has been completed for this case.</p>
          )}
        </div>

        <div className="rp-disclaimer">
          <strong>IMPORTANT DISCLAIMER</strong>
          <p>This is a research and demonstration prototype. The measurements, potential anatomical matches, AI-associated analysis, and incomplete surgical planning presented here have not been clinically validated and must not be used for diagnosis, surgical planning, or direct patient care. Final clinical interpretation is the sole responsibility of the attending physician.</p>
        </div>
      </div>

      <div className="rp-actions">
        <Button variant="ghost" onClick={onBack}>&larr; Back to Planning</Button>
        <div className="rp-primary-actions">
          <Button variant="secondary" onClick={() => window.print()}>Print Report</Button>
          <Button variant="primary" onClick={onNewCase}>Start New Case</Button>
        </div>
      </div>
    </div>
  );
};
