import React from 'react';
import type { CaseState, CaseImage } from '../types/case';
import { Button } from '../components/ui/Button';
import './Report.css';

interface ReportProps {
  caseState: CaseState;
  onBack: () => void;
  onNewCase: () => void;
}

export const Report: React.FC<ReportProps> = ({ caseState, onBack, onNewCase }) => {
  
  const renderImageSummary = (img: CaseImage) => (
    <div key={img.id} className="rp-study-card">
      <h4>{img.metadata?.modality} • {img.file?.name}</h4>
      <div className="rp-study-grid">
        <div className="rp-study-col">
          <span className="rp-label">Femur</span>
          <span className="rp-val">{img.measurements.bones?.femur?.width_mm ? `${img.measurements.bones.femur?.width_mm.toFixed(1)} mm` : 'N/A'}</span>
        </div>
        <div className="rp-study-col">
          <span className="rp-label">Tibia</span>
          <span className="rp-val">{img.measurements.bones?.tibia?.width_mm ? `${img.measurements.bones.tibia?.width_mm.toFixed(1)} mm` : 'N/A'}</span>
        </div>
        {img.metadata?.modality === 'MRI' && (
          <div className="rp-study-col">
            <span className="rp-label">Meniscus</span>
            <span className="rp-val">{img.measurements.meniscus?.mean_thickness_mm ? `${img.measurements.meniscus.mean_thickness_mm.toFixed(2)} mm` : 'N/A'}</span>
          </div>
        )}
      </div>
    </div>
  );

  return (
    <div className="rp-container fade-in">
      <div className="rp-document">
        <div className="rp-header">
          <h1>KNEE AI WORKSTATION</h1>
          <p>Research Prototype • Case Report</p>
        </div>

        <div className="rp-section">
          <h2>Patient Information</h2>
          <div className="rp-grid">
            <div className="rp-item">
              <span className="rp-label">Patient Name</span>
              <span className="rp-val">{caseState.patient.name || 'Unknown'}</span>
            </div>
            <div className="rp-item">
              <span className="rp-label">Age / Sex</span>
              <span className="rp-val">{caseState.patient.age || '-'} / {caseState.patient.sex || '-'}</span>
            </div>
            <div className="rp-item">
              <span className="rp-label">Case ID</span>
              <span className="rp-val">{caseState.caseId}</span>
            </div>
            <div className="rp-item">
              <span className="rp-label">Laterality</span>
              <span className="rp-val">{caseState.patient.laterality || '-'}</span>
            </div>
          </div>
          <div className="rp-notes">
            <strong>Clinical Notes:</strong>
            <p>{caseState.patient.notes || 'None provided.'}</p>
          </div>
        </div>

        <div className="rp-section">
          <h2>Imaging Studies ({caseState.images.length})</h2>
          <div className="rp-studies-list">
            {caseState.images.map(renderImageSummary)}
          </div>
        </div>

        {caseState.oaAnalysis && (
          <div className="rp-section">
            <h2>OA-Associated Findings</h2>
            <div className="rp-grid">
              <div className="rp-item">
                <span className="rp-label">Joint Space Narrowing</span>
                <span className="rp-val">{caseState.oaAnalysis.patient_findings.joint_space_narrowing}</span>
              </div>
              <div className="rp-item">
                <span className="rp-label">Osteophytes</span>
                <span className="rp-val">{caseState.oaAnalysis.patient_findings.osteophytes}</span>
              </div>
            </div>
          </div>
        )}

        <div className="rp-disclaimer">
          <strong>IMPORTANT DISCLAIMER</strong>
          <p>This is a research and demonstration prototype. The analysis generated by this report is not validated for clinical diagnosis, surgical decision-making, or direct patient care.</p>
        </div>
      </div>

      <div className="rp-actions">
        <Button variant="ghost" onClick={onBack}>&larr; Back to Planning</Button>
        <div className="rp-primary-actions">
          <Button variant="secondary" onClick={() => window.print()}>Print Report</Button>
          <Button variant="primary" onClick={onNewCase}>Start New Case</Button>
        </div>
      </div>
    </div>
  );
};
